# Generated by Django 4.2.2 on 2023-06-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='protocol',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], max_length=10),
        ),
    ]
