export const SOCIAL = {
    github: "",
    twitter: "",
    linkedin: "",
    instagram: "",
    facebook: "",
    youtube: "",
    twitch: "",
    discord: "",
    reddit: "",
    medium: "",
    devto: "",
    patreon: "",
    tiktok: "",
}